export const sampler_projects: ProjectList = [
  {
    title: 'Crossify',
    category: 'Event and Club driven social media',
    skills: [
      'React.js',
      'Express.js',
      'Node.js',
      'MongoDB',
      'Tailwind',
      'Material-UI',
      'Redux',
      'REST-APIs',
      'OAuth',
      'Google Maps Api',
      'Socket.io',
      'Chart.js',
      'Passport',
      'SMTP server',
      'Cloudinary',
    ],
    live_link: 'https://crossify.vercel.app/',
    github_link: 'https://github.com/hackershil/crossify',
    redirect_link: '/projects/crossify',
    warning: null,
    image_url: '/image/crossify-smooth.gif',
    color: '#C0D6E8',
  },
  {
    title: 'Invoice Automation',
    category: 'Invoice Parser | Extractor | Visualizer',
    skills: [
      'React.js',
      'Express.js',
      'Node.js',
      'MongoDB',
      'RegEx',
      'EUI',
      'Redux',
      'Context API',
      'REST-APIs',
      'Chart.js',
      'Swagger',
      'Multer',
      'Passport',
      'JWT',
      'PDF.js',
      'Winston',
    ],
    live_link: 'https://meekneil.vercel.app/',
    github_link: 'https://github.com/hackershil/invoice-automation-client',
    redirect_link: '/projects/invoice-automation',
    warning: null,
    image_url: '/image/invoice-automation-poster.gif',
    color: '#C0D6E8',
  },
  // {
  //   title: 'Harbor',
  //   category: 'Full Stack AI-Enhanced Music Discovery Platform',
  //   skills: [
  //     'Next.js',
  //     'React.js',
  //     'Tailwind',
  //     'Firebase',
  //     'Zustand',
  //     'Shadcnui',
  //     'NextAuth',
  //     'OpenAI Api',
  //     'Spotify Api',
  //   ],
  //   live_link: null,
  //   github_link: 'https://github.com/yeahimjt/harbor',
  //   redirect_link: '/projects/harbor',
  //   warning:
  //     'Due to Spotify classifying my project as a hobby, only manually selected users can access it. If you wish to demo the application please reach out by email.',
  //   image_url: '/image/harbor.png',
  //   color: '#CCE3D5',
  // },
  // {
  //   title: 'Clinkz',
  //   category: 'Full Stack Amazon Price Tracker With Subscriptions',
  //   skills: [
  //     'Next.js',
  //     'React.js',
  //     'Tailwind',
  //     'Firebase',
  //     'Zustand',
  //     'Shadcnui',
  //     'NextAuth',
  //   ],
  //   live_link: 'https://clinkz.vercel.app/',
  //   github_link: 'https://github.com/yeahimjt/clinkz',
  //   redirect_link: '/projects/clinkz',
  //   warning: null,
  //   image_url: '/image/clinkz.png',
  //   color: '#D4D0E1',
  // },
];

export const sampler_experience: ExperienceList = [
  {
    title: 'Master of Science in Software Engineering',
    timeframe: 'Aug 2023 - May 2025',
    company: 'San Jose State University',
    description:
      'Specialization - Enterprise Software Technologies , Coursework - Software Systems Engineering, Data Mining, Enterprise Distributed Systems, Enterprise Software Platforms, Machine Learning',
  },
  {
    title: 'Software Engineer',
    timeframe: 'Jul 2021 - Jul 2023',
    company: 'AIVIDTechvision Pvt Ltd',
    description:
      'Led the development of an analytics platform for video intelligence in computer vision products. Achievements include optimizing data storage, automating dashboard creation, and extracting actionable insights from large data volumes, resulting in significant cost and time savings. Expertise in server implementation using Hapi, integration of Elasticsearch and Kubernetes, and streamlining CI/CD pipelines with GitHub Actions. ',
  },
  {
    title: 'Software Engineer Intern',
    timeframe: 'Apr 2021 - Jun 2021',
    company: 'AIVIDTechvision Pvt Ltd',
    description:
      'Developed a Typescript backend with Express.js for worker node operations, enabling live snapshots and metadata handling. Introduced Dev Insights for efficient model evaluation, reducing manual efforts by 90%. Streamlined developer environment setup and deployment processes with Bash scripts, saving 60% setup time. Engineered an automated Inspection Report system using Puppeteer and NodeJS, delivering scheduled business updates with charts, CSVs, and camera content.',
  },
  {
    title: 'Frontend Engineer Intern',
    timeframe: 'Mar 2021 - Apr 2021',
    company: 'Srchout',
    description:
      'Developed an E-learning platform using Angular and Material-UI integrated features such as statistical analysis of student, dashboards, Live E-board, Zoom WebSDK.',
  },
  {
    title: 'Bachelor of Engineering in Information Technology',
    timeframe: 'Aug 2017 - May 2021',
    company: 'Gujarat Technological University',
    description:
      'Coursework - Data structures, Object oriented programming - C++/Java, Analysis and Design of Algorithms, Python programming, Web Technology, Data mining and Business Intelligence, Big Data Analytics, Artificial Intelligence ',
  },
];

export const achievements: ExperienceList = [
  {
    title: 'Top 1.25% in CodeChef October Challenge',
    timeframe: 'Oct 2020',
    company: 'CodeChef',
    description: '263 out of 20,000+ participants',
  },
  {
    title: 'Top 1.19% in CodeChef September Challenge',
    timeframe: 'Sep 2020',
    company: 'CodeChef',
    description: '357 out of 30,000+ participants',
  },
  {
    title: 'Top 3.5% in Facebook Hackercup round',
    timeframe: 'Oct 2020',
    company: 'Facebook Hackercup',
    description: '1167 out of 32,000+ participants',
  },
  {
    title: 'Secured 886 Rank in CodeChef July Challenge',
    timeframe: 'July 2020',
    company: 'CodeChef Hackercup',
    description:
      'solved 7 problems with 1 partially right solution out of 10 problems(15 Days long Competition)',
  },
  {
    title: 'Secured 1166 Rank in CodeVita 2020 Round 1',
    timeframe: 'Aug 2020',
    company: 'CodeVita 2020',
    description: 'Highest Rank in the college.',
  },
];

export const skills = [
  'next',
  'react',
  'tailwind',
  'javascript',
  'typescript',
  'firebase',
  'express',
  'aws',
  'azure',
  'mysql',
  'mongo',
  'java',
  'c',
  'python',
  'csharp',
];
